### ISSUE TITLE
Permission errors during installation (`dcor inspect`) in a Docker container

### ISSUE THREAD

**Issue by RaghavaAlajangi** [DCOR-dev/dcor_control#23]
When I run `dcor inspect` inside a Docker container to set the values in `ckan.ini`, I get the below errors:

```
Checking CKAN options...
Please enter 'pgsqlpass': pass
Setting 'ckan.auth.create_user_via_api=true' (was 'false').
Setting 'ckan.auth.create_user_via_web=true' (was 'false').
Setting 'ckan.site_title=DCOR-Docker' (was 'CKAN').
Setting 'dcor_object_store.access_key_id=minioadmin' (was 'NOT SET!').
Setting 'dcor_object_store.secret_access_key=minioadmin' (was 'NOT SET!').
Setting 'dcor_object_store.endpoint_url=http://127.0.0.1:9000' (was 'NOT SET!').
Setting 'dcor_object_store.ssl_verify=false' (was 'NOT SET!').
Setting 'ckan.storage_path=/data/ckan-dcor-docker-test' (was '/var/lib/ckan/default').
Setting 'ckan.auth.create_dataset_if_not_in_organization=false' (was 'true').
Setting 'ckan.auth.user_delete_groups=false' (was 'true').
Setting 'ckan.auth.user_delete_organizations=false' (was 'true').
Setting 'ckan.auth.public_user_details=false' (was 'true').
Setting 'ckan.auth.allow_dataset_collaborators=true' (was 'false').
Setting 'dcor_object_store.bucket_name=circle-{organization_id}' (was 'NOT SET!').
Setting 'ckan.favicon=/favicon.ico' (was '/base/images/ckan.ico').
Setting 'ckan.gravatar_default=disabled' (was 'identicon').
Setting 'ckan.max_resource_size=100000' (was '10').
Setting 'ckan.plugins=stats text_view image_view dcor_depot dcor_schemas dc_serve dc_view dc_log_view dcor_theme' (was 'image_view text_view datatables_view datastore datapusher envvars').
Setting 'ckan.views.default_views=image_view text_view dc_view dc_log_view' (was 'image_view datatables_view').
Setting 'ckan.webassets.path=/var/lib/ckan/webassets' (was '').
Setting 'solr_url=http://localhost:8983/solr/ckan' (was 'http://127.0.0.1:8983/solr/ckan').
Setting 'ckanext.dc_serve.create_condensed_datasets=true' (was 'NOT SET!').
Setting 'ckanext.dc_serve.tmp_dir=/data/tmp/ckanext-dc_serve' (was 'NOT SET!').
Setting 'ckanext.dcor_depot.depots_path=/data/depots' (was 'NOT SET!').
Setting 'ckanext.dcor_depot.users_depot_name=users-dcor-docker-test' (was 'NOT SET!').
Setting 'ckan.extra_resource_fields=etag sha256' (was '').
Setting 'ckanext.dcor_schemas.allow_content_listing_for_anon=true' (was 'NOT SET!').
Setting 'ckanext.dcor_schemas.allow_public_datasets=true' (was 'NOT SET!').
Setting 'ckanext.dcor_schemas.json_resource_schema_dir=package' (was 'NOT SET!').
Setting 'ckan.csrf_protection.ignore_extensions=false' (was 'true').
Setting 'beaker.session.cookie_expires=7776000' (was 'NOT SET!').
Setting 'beaker.session.crypto_type=cryptography' (was 'NOT SET!').
Setting 'beaker.session.domain=dcor-docker-test' (was 'NOT SET!').
Setting 'beaker.session.data_serializer=pickle' (was 'NOT SET!').
Setting 'beaker.session.httponly=true' (was 'NOT SET!').
Setting 'beaker.session.samesite=Strict' (was 'NOT SET!').
Setting 'beaker.session.secure=true' (was 'NOT SET!').
Setting 'beaker.session.type=cookie' (was 'NOT SET!').
Setting 'REMEMBER_COOKIE_DURATION=7776000' (was '31536000').
Setting 'REMEMBER_COOKIE_SECURE=true' (was 'false').
Setting 'REMEMBER_COOKIE_SAMESITE=Strict' (was 'None').
Checking beaker session secret...
Setting 'beaker.session.encrypt_key=dc42fc11-7f37-4d9c-8ee4-6b83cd38cc99' (was 'NOT SET!').
Setting 'beaker.session.validate_key=f1e0daad-e670-4ccf-ad88-6531c835ac47' (was 'NOT SET!').
Checking www-data permissions...
Creating directory '/data/ckan-dcor-docker-test'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/data/ckan-dcor-docker-test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/app/.local/bin/dcor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/srv/app/.local/lib/python3.10/site-packages/dcor_control/cli/inspect.py", line 44, in inspect
    cn += inspect_mod.check_permission(
  File "/srv/app/.local/lib/python3.10/site-packages/dcor_control/inspect/common.py", line 74, in check_permission
    path.mkdir(parents=True)
  File "/usr/local/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/data'
``` 
In addition,
```
ckan11-dcor-dev-1  | Traceback (most recent call last):
ckan11-dcor-dev-1  |   File "/usr/local/bin/ckan", line 8, in <module>
ckan11-dcor-dev-1  |     sys.exit(ckan())
ckan11-dcor-dev-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
ckan11-dcor-dev-1  |     return self.main(*args, **kwargs)
ckan11-dcor-dev-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1077, in main
ckan11-dcor-dev-1  |     with self.make_context(prog_name, args, **extra) as ctx:
ckan11-dcor-dev-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 943, in make_context
ckan11-dcor-dev-1  |     self.parse_args(ctx, args)
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/cli/cli.py", line 120, in parse_args
ckan11-dcor-dev-1  |     result = super().parse_args(ctx, args)
ckan11-dcor-dev-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1644, in parse_args
ckan11-dcor-dev-1  |     rest = super().parse_args(ctx, args)
ckan11-dcor-dev-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1408, in parse_args
ckan11-dcor-dev-1  |     value, args = param.handle_parse_result(ctx, opts, args)
ckan11-dcor-dev-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2400, in handle_parse_result
ckan11-dcor-dev-1  |     value = self.process_value(ctx, value)
ckan11-dcor-dev-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2362, in process_value
ckan11-dcor-dev-1  |     value = self.callback(ctx, self, value)
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/cli/cli.py", line 130, in _init_ckan_config
ckan11-dcor-dev-1  |     _add_ctx_object(ctx, value)
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/cli/cli.py", line 139, in _add_ctx_object
ckan11-dcor-dev-1  |     ctx.obj = CtxObject(path)
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/cli/cli.py", line 56, in __init__
ckan11-dcor-dev-1  |     self.app = make_app(raw_config)
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 29, in make_app
ckan11-dcor-dev-1  |     load_environment(conf)
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/config/environment.py", line 68, in load_environment
ckan11-dcor-dev-1  |     p.load_all()
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 148, in load_all
ckan11-dcor-dev-1  |     load(*plugins)
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 180, in load
ckan11-dcor-dev-1  |     plugins_update()
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 136, in plugins_update
ckan11-dcor-dev-1  |     environment.update_config()
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/config/environment.py", line 134, in update_config
ckan11-dcor-dev-1  |     plugin.update_config(config)
ckan11-dcor-dev-1  |   File "/srv/app/.local/lib/python3.10/site-packages/ckanext/dcor_schemas/plugin.py", line 118, in update_config
ckan11-dcor-dev-1  |     toolkit.get_action('config_option_update')(
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/logic/__init__.py", line 580, in wrapped
ckan11-dcor-dev-1  |     result = _action(context, data_dict, **kw)
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/logic/action/update.py", line 1264, in config_option_update
ckan11-dcor-dev-1  |     upload = uploader.get_uploader('admin')
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/lib/uploader.py", line 61, in get_uploader
ckan11-dcor-dev-1  |     upload = Upload(upload_to, old_filename)
ckan11-dcor-dev-1  |   File "/srv/app/src/ckan/ckan/lib/uploader.py", line 129, in __init__
ckan11-dcor-dev-1  |     os.makedirs(self.storage_path)
ckan11-dcor-dev-1  |   File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
ckan11-dcor-dev-1  |     mkdir(name, mode)
ckan11-dcor-dev-1  | PermissionError: [Errno 13] Permission denied: '/var/lib/ckan/storage/uploads/admin'
ckan11-dcor-dev-1  | Exit with status 1. Restarting.

```

Issues:
- permission error while accessing the `/data` dir
- `dcor_schemas` also triggers another permission error while accessing the `'/var/lib/ckan/storage/uploads/admin'`

**Comment by paulmueller** [comment]
Regarding the `/data` directory: In the new recipe (#21) I changed this directory to `/tmp`, but this of course is not persistent. You can modify the storage path to something that resembles a reasonable default:

https://github.com/DCOR-dev/dcor_control/blob/0.12.0/dcor_control/resources/site_dcor-docker/dcor_config.json#L11

I am looking into the other issue...

**Comment by paulmueller** [comment]
The second problem is not related to `dcor_schemas` after all.
You should be able to fix it (as root) via

```
mkdir -p /var/lib/ckan/storage/uploads/admin
chown -R CKAN_USER /var/lib/ckan/storage
```

**Comment by paulmueller** [comment]
As far as I can tell this is resolved.
